# Generated by Django 5.2.6 on 2025-11-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer_item_no', models.CharField(blank=True, max_length=128, null=True)),
                ('upc_code', models.CharField(blank=True, max_length=14, null=True)),
                ('box_upc', models.CharField(blank=True, max_length=14, null=True)),
                ('inner_pack_upc', models.CharField(blank=True, max_length=14, null=True)),
                ('alternative_upc_1', models.CharField(blank=True, max_length=14, null=True)),
                ('alternative_upc_2', models.CharField(blank=True, max_length=14, null=True)),
                ('alternative_upc_3', models.CharField(blank=True, max_length=14, null=True)),
                ('size', models.CharField(blank=True, max_length=64, null=True)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('qtyss', models.FloatField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('locations', models.CharField(choices=[('outside', 'Outside'), ('inside', 'Inside')], default='outside', max_length=16)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('tax_group_id', models.IntegerField(blank=True, null=True)),
                ('price_group_id', models.IntegerField(blank=True, null=True)),
                ('cash_discount_group_id', models.IntegerField(blank=True, null=True)),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('items_to_be_sold_by_units', models.BooleanField(default=True)),
                ('include_in_msa', models.BooleanField(default=True)),
                ('identification_symbol', models.CharField(blank=True, max_length=64, null=True)),
                ('distribution_sku', models.CharField(blank=True, max_length=64, null=True)),
                ('item_per_selling_unit', models.CharField(blank=True, max_length=64, null=True)),
                ('promotion_indicator', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('product_unit_size_description', models.TextField(blank=True, null=True)),
                ('msa_category_code', models.CharField(blank=True, max_length=64, null=True)),
                ('distributor_product_unit_size', models.CharField(blank=True, max_length=64, null=True)),
                ('is_cash_and_carry', models.BooleanField(default=True)),
                ('cash_and_carry_item_code', models.CharField(blank=True, max_length=64, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('gallery', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('default_price', models.FloatField(blank=True, null=True)),
                ('other_information', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
                'managed': True,
            },
        ),
    ]
