# Generated by Django 5.2.6 on 2025-11-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amazon_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
